name: Auto Format and Commit

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  format-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Prettier
        run: npm install prettier

      - name: Run Prettier to auto-fix code including HTML
        run: npx prettier --write "**/*.{js,ts,json,css,md,html}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && echo "No changes to commit" || (git commit -m "chore: auto-format code" && git push)
