name: Schedule Clear Current Game

on:
  workflow_dispatch:   # Manual run button
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  call-supabase-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        env:
          SUPABASE_FUNCTION_URL: ${{ secrets.SUPABASE_FUNCTION_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -X POST "$SUPABASE_FUNCTION_URL" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/json"
